### ISSUE TITLE
Lisp error: (void-variable left) after update

### ISSUE THREAD

**Issue by joonro** [kuanyui/moe-theme.el#55] opened 2015-03-13 06:16 UTC
Hi,

I just updated the theme to 20150307.1907 from melpa. When I'm restarting Emacs, I'm getting the following error:

```lisp
Debugger entered--Lisp error: (void-variable left)
  powerline-reset()
  require(powerline nil :no-error)
  byte-code("\300\301\302\303#\203
```

(For some reason I cannot copy the the full traceback)

Powerline got updated to (to `20150312.2049`), but even when I comment out all the `powerline` stuff in my init file and have `(require 'moe-theme)` only, I still get the same error.

**Comment by kuanyui** [comment] 2015-03-13 06:19
Which powerline package is you're using?

**Comment by joonro** [comment] 2015-03-13 06:25
I have been using this one: https://github.com/milkypostman/powerline/

**Comment by lurdan** [comment] 2015-03-13 08:23
I've met same issue, and recovered as:
1. delete package moe-theme and powerline and restart emacs
2. install moe-theme and restart emacs
3. install powerline and restart emacs

I'm not sure that every restarting is necessary

**Comment by kuanyui** [comment] 2015-03-13 09:41
Sorry, I cannot reproduct the issue on 24.3.1.
Can you elaborate it? Include Emacs version, configurations, and make sure test under a clean Emacs (`emacs -Q`).

**Comment by arpunk** [comment] 2015-03-13 12:14
I just hitted this issue and starting to use solarized as a temporarly solution. I am also using that same `powerline` version that @joonro is using. @kuanyui I'm going to try your workaround and see if it helps, thanks!

**Comment by kuanyui** [comment] 2015-03-13 13:00
Anyone can give me more detailed information to find out where the problem is? I just created a new user on my system, tested on an totally clean Emacs 24.4.1  (`emacs -Q`, without window system) ; installed only `moe-theme` and `powerline` via MELPA; with minimum config file:

```lisp
(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)

;; If you want to use powerline, (require 'powerline) must be
;; before (require 'moe-theme).
(require 'powerline)

(require 'moe-theme)
(moe-light)
(powerline-moe-theme)
                                
``` 

And just cannot reproduced the issue you encountered.

@arpunk What did you mean? I've not provided any workaround...

**Comment by lurdan** [comment] 2015-03-13 14:03
I don't know how, but can I install specific old version of melpa package?

I guess that it is something compile/macro/timing issue, which caused by powerline update including some "left" keywords.
(cf. https://github.com/milkypostman/powerline/compare/66cf0fdf7637ca3d65b82d12124d39c7d7f8b215...master)

so, to reproduce this, at first I should  install powerline-20141126 with moe-theme, and upgrade powerline to current version.

p.s. I use emacs24.4 (debian sid package) with melpa packages.

**Comment by kuanyui** [comment] 2015-03-13 14:37
It seems that no way to install specific version in MELPA repo unless you git clone and checkout by yourself.

I still cannot understand why do you need to install an old version powerline (20141126)? I just tried latest version of both packages and doesn't encounter the issue you've described.

    moe-theme-20150307.1907 
    powerline-20150312.2049

To report a valid bug report, please make sure:

1. Start Emacs with `emacs -Q` and make sure that *only* the settings of `moe-theme` and `powerline` be evaluated. If you're not familiar with this, create a new user and edit the `~/.emacs.d/init.el` of it.
2. Installed the latest versions on MELPA, then restart Emacs.
3. If the problem still exists, please restart Emacs with `emacs --debug-init` and post the error message.

**Comment by joonro** [comment] 2015-03-13 17:26
One thing is that even if I do not require `powerline`, if it is installed, then mere `(require 'moe-theme)` causes this error. (I commented out `;(require 'powerline)`). 

I just uninstalled `powerline` it now Emacs loads fine. I will try to reinstall it.

**Comment by joonro** [comment] 2015-03-13 17:30
Okay. Just removing `powerline` (I restarted Emacs - I'm not sure this is required) and then reinstalling it fixed my problem. I wonder in the last update there were some garbage stuff not cleaned up.

**Comment by lurdan** [comment] 2015-03-15 01:11
To be clear:

I myself have already avoided this issue (as first I posted).
So, installing current versions cleanly doesn't cause any problem. (Also I think that the issue is powerline's, not moe-theme's. You can close this issue because moe-theme simply suffered when it (require 'powerline) internally).

Have I made myself understood this time?

--
Anyway, I've created the emacs.d which can reproduce the problem.
https://github.com/lurdan/emacs-d-powerline-update

1. checkout this repository, and setup as your .emacs.d
2. emacs -Q -l .emacs.d/init.el
3. evaluate (list-packages) and update powerline
4. restart emacs and you will see the error which oiginal poster met

**Closed** 2015-05-08 18:46 UTC
