### ISSUE TITLE
buffer name square around

### ISSUE THREAD

**Issue by mashu** [kuanyui/moe-theme.el#82] opened 2016-10-29 10:43 UTC
Hi,

Attached screen shows that buffer name "emacs-init.org" has not consistent orange color when not in focus. The square around it looks ugly.

My config you can also see in the attached screenshot or [here](https://github.com/mashu/Emacs/blob/October2016/emacs-init.org#appearance)
![emacs](https://cloud.githubusercontent.com/assets/78471/19828961/e8cfcb62-9dd4-11e6-9fb2-5db58a54da46.png)

Thanks for help!

**Comment by kuanyui** [comment] 2016-10-29 12:06
I guess `(setq moe-theme-mode-line-color 'orange)`  and `(moe-dark)` are the reason.

Try to remove the two lines, just use `(load-theme 'moe-dark)`.

**Comment by mashu** [comment] 2016-10-29 14:20
I try this

![emacs2](https://cloud.githubusercontent.com/assets/78471/19830220/66f756e0-9df3-11e6-9c98-e148c667a052.png)


As suggested I removed those lines and use only what you state on your website.
Theme looks good when in focus (except of white strip which I dont like) but when buffer is not active  see attached picture rectangle around buffer name.

**Comment by kuanyui** [comment] 2016-10-30 06:29
If you want to use `(powerline-moe-theme)`, use `(moe-dark)`.
If you don't want to use `(powerline-mode-them)`, use `(load-them 'moe-dark)`

I also feel this is so annoying...

**Comment by mashu** [comment] 2016-10-30 07:46
Thanks, however my problem is still present. 
![diffemacs](https://cloud.githubusercontent.com/assets/78471/19835128/0f4eed06-9e7d-11e6-8d7b-73f4b6ebb590.png)

Here is config
```
(use-package powerline
  :ensure t
  ;;:init (powerline-default-theme)
  :config
  ;; (setq powerline-default-separator 'wave)
  (use-package moe-theme
    :ensure t
    :config
    ;;(setq moe-theme-mode-line-color 'orange)
    (moe-dark)
    ;;(load-theme 'moe-dark)
    (powerline-moe-theme)
    ;; Highlight block with matching parens
    (show-paren-mode t)
    (setq show-paren-style 'expression)
    )
  )
```

**Comment by kuanyui** [comment] 2016-10-30 13:48
Sorry, I cannot reproduce your issue on my system. (Both console & GUI Emacs. Emacs 25.1, latest moe-theme & powerline)
![md8](https://cloud.githubusercontent.com/assets/1370070/19836951/4a9b0f94-9eea-11e6-9a09-9af760b14138.png)

BTW, There are a lot of implements of powerline, are you sure the powerline you're using is this one?
![md8](https://cloud.githubusercontent.com/assets/1370070/19836962/7c374b30-9eea-11e6-93c1-17a3069df4e9.png)

**Comment by mashu** [comment] 2016-10-30 14:25
Hi,
Looks like i have exactly the same version.
![emacs2](https://cloud.githubusercontent.com/assets/78471/19836992/9ef209c4-9eb0-11e6-9fe9-4c37dcf1f787.png)

Steps to reproduce.

1. Start emacs
2. C-x 2 to split window in two
3. Click other application window (i.e browser but not emacs window) to lose focus on Emacs
4. Use Alt+Tab to select Emacs window again
5. Active buffer is not blue entirely, just the buffer name

When I click inside Emacs on each buffer, they select blue correctly and inactive is also correct. But when I lose focus on Emacs window and come back with Alt+Tab, previously active buffer is not highlighted correctly.

I made a short 57 sec screencast of the problem seen at the end of movie
https://vimeo.com/189513267

**Comment by kuanyui** [comment] 2016-10-30 15:34
Ugh! If the issue involve the WM/DE on your system...It seems beyond the range which I can handle.

Your screencast looks indeed very bizarre, it looks you're using GNOME3 + GUI version Emacs. I just tested on KDE5 & OS X + GUI Emacs, but both cannot reproduce the phenomenon you encountered. 

I'm not sure this issue is due to Emacs itself or moe-theme... Because I still cannot reproduce what you've encountered, maybe you can try to [take a look of the code of the related part](https://github.com/kuanyui/moe-theme.el/blob/master/moe-theme.el#L475-L482) and modifying by yourself until it solve the problem, L475~482 handle powerline faces. If really solved, feel free to share your patch. ;)

(BTW, your issue only occurs when Emacs losing its focus, I don't think that's a unacceptable issue. :sweat: . But about Helm... I also encountered. It may be unsolveable, or more precisely --- I have no patience and free time to see what Helm have done on mode-line for such a subtle bug.)

![md8](https://cloud.githubusercontent.com/assets/1370070/19837628/987211c8-9ef8-11e6-8dc7-5afd1dc29bd8.png)

**Comment by choma** [comment] 2016-10-31 17:46
I can confirm the issue.
I'm using emacs 24. `M-x emacs-version` shows :

> GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.21.5) of 2016-09-05 on trouble, modified by Debian

I'm on gnome 3 (version 3.22.1).

**Comment by mashu** [comment] 2016-11-01 10:06
@kuanyui in your screenshot you have the same problem as me and @choma The *scratch* has grey right triangle which should be forest green color. 

I disabled loading of helm completely, and problem persists, so it's not Helm fault I think.
Then I disabled loading of every package except for powerline and moe-theme, same problem.

@choma I am also using Debian, would it be possible to try on Ubuntu by someone ?

**Comment by kuanyui** [comment] 2016-11-04 18:09
This issue should not be related to distro, window manager instead, I guess.

>@kuanyui in your screenshot you have the same problem as me and @choma The *scratch* has grey right triangle which should be forest green color. 
>

You were misunderstood. On KDE, I have not any problem you've encountered except for Helm. 

>I disabled loading of helm completely, and problem persists, so it's not Helm fault I think.
Then I disabled loading of every package except for powerline and moe-theme, same problem.

Sorry, I don't have any idea.

**Comment by choma** [comment] 2016-11-06 13:23
I guess this is not a moe-theme issue, but a powerline one, see:
* [focus-out-hook causing wrong colors on Mac](https://github.com/milkypostman/powerline/issues/135), and
* [powerline does not detect the "active" modeline correctly](https://github.com/milkypostman/powerline/issues/37)

I think this should be closed.

**Comment by angelovalderrama** [comment] 2017-05-08 09:52
Same issue, it's a powerline problem, close this issue...

**Closed** 2018-05-07 15:05 UTC
Labels: invalid
